name: Ruby Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.8'
          bundler-cache: true # This enables caching of gems and runs bundle install

      - name: Run Minitest tests
        run: bundle exec ruby test/app_test.rb
